# Generated by Django 5.1 on 2024-08-27 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborated_itineraries', to=settings.AUTH_USER_MODEL),
        ),
    ]
