# Generated by Django 5.1 on 2024-08-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0003_alter_itinerary_user_itineraryday_itinerarylocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
