# Generated by Django 5.1 on 2024-08-28 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('countries', '0001_initial'),
        ('itineraries', '0002_itinerary_collaborators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='categories.category')),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='countries.location')),
                ('itin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='itineraries.itinerary')),
                ('loc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='countries.location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
