# Generated by Django 5.1 on 2024-08-28 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        ('itineraries', '0002_itinerary_collaborators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCollection',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('itin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries_collection', to='itineraries.itinerary')),
                ('loc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations_collection', to='countries.location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_collection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
